// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: feed_posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFeedPost = `-- name: CreateFeedPost :exec
INSERT INTO feed_posts (id, title, description, url, feed_id, published_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, description, url, feed_id, published_at, created_at, updated_at
`

type CreateFeedPostParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Url         string         `json:"url"`
	FeedID      uuid.UUID      `json:"feed_id"`
	PublishedAt time.Time      `json:"published_at"`
}

func (q *Queries) CreateFeedPost(ctx context.Context, arg CreateFeedPostParams) error {
	_, err := q.db.ExecContext(ctx, createFeedPost,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.FeedID,
		arg.PublishedAt,
	)
	return err
}
